# 此工作流使用未经 GitHub 认证的操作。
# 它们由第三方提供，并受
# 单独的服务条款、隐私政策和支持
# 文档管理。
# refs https://docs.github.com/cn/actions/publishing-packages/publishing-docker-images

name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_docker:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: shadowu/wuh.site
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build_container:
    name: Build Container
    runs-on: ubuntu-latest
    needs: [push_to_docker]
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker ps -a
            echo "[github bot] version:" ${{ needs.push_to_docker.outputs.tags }}
            cd /home/next-web-app/frontend
            ./bin/clear-docker.sh
            ./bin/build-container.sh ${{ needs.push_to_docker.outputs.tags }}
      # - name: executing remote ssh commands using password
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.KEY }}
      #     port: ${{ secrets.PORT }}
      #     script: |
      #       echo '============== docker build contianer ==========='
      #       echo '构建container的版本号: ' ${{ steps.meta.outputs.tags }}

      #       docker ps -a | grep 'frontend.' | awk '{print $1}' | xargs docker stop
      #       docker ps -a | grep 'frontend.' | awk '{print $1}' | xargs docker rm
      #       docker pull shadowu/wuh.site:latest
      #       docker container run --name frontend.${{ steps.meta.outputs.tags }}\
      #       -it\
      #       -p 3100:3000\
      #       --restart=always shadowu/wuh.site:latest

      #       systemctl status docker
      #       systemctl restart nginx

      #       echo '============== docker build successfully =================='
