name: Release Drafter

on: 
  push: 
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update_release_drafter:
    runs-on: ubuntu-latest
    steps:
      - name: Chekcout
        uses: actions/checkout@v2
      - name: Create Release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # restart_docker_nginx:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Chekcout
  #       uses: actions/checkout@v2
  #     - name: executing remote ssh commands using password
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.USERNAME }}
  #         key: ${{ secrets.KEY }}
  #         port: ${{ secrets.PORT }}
  #         script: |
  #           whoami
  #           cd /home/next-web-app/frontend/

  #           git reset --hard HEAD~~
  #           git pull origin main


