name: Release Drafter

on: 
  push: 
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update_release_drafter:
    runs-on: ubuntu-latest
    steps:
      - name: CREATE RELEASE
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
